version: '3.1'

services:
  mongo:
    image: mongo:7.0.12
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: your_password
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
